[tool.poetry]
name = "semsim"
version = "0.1.0"
description = ""
authors = ["Justin Reese <justaddcoffee@gmail.com>",
"Harshad Hegde" <hhegde@lbl.gov>,
"J. Harry Caufield" <jhc@lbl.gov>
]
readme = "README.md"
licens

[tool.poetry.dependencies]
python = "^3.9"
grape = "^0.1.10"
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]
Sphinx = "^5.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
